### ISSUE TITLE
Complete current overhaul

### ISSUE THREAD

**Issue by Domochevsky** [Domochevsky/minecraft-quiverbow#3]
The last time I was working on QB I was in the middle of a large overhaul, changing from arrays[] to ArrayLists<> among other things. This leaves it with ...about 670 cascade errors at the moment.

In order to get the current build (b102) even working this will have to be completed first.

**Comment by Daomephsta** [comment]
#4

**Comment by Domochevsky** [comment]
Whelp, that was quick. :)
